apiVersion: apps/v1
kind: Deployment
metadata:
  name: crafty-project
  namespace: crafty
spec:
  selector:
    matchLabels:
      app: crafty
  template:
    metadata:
      labels:
        app: crafty
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          image: kuranasaki/crafty-frontend
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
          - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: crafty-env
                  key: NEXT_PUBLIC_FIREBASE_API_KEY
            - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              value: "crafty-4e7fc.firebaseapp.com"
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              value: "crafty-4e7fc"
            - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              value: "crafty-4e7fc.appspot.com"
            - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              value: "512308057994"
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              value: "1:512308057994:web:150e92b7bedead71f65a73"
            - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
              value: "G-NGYDT9MKKY"
        - name: backend
          imagePullPolicy: Always
          image: kuranasaki/crafty-backend
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
          - containerPort: 8000
          env:
            - name: MONGODB_NAME
              value: "crafty-dev"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: crafty-env
                  key: MONGODB_URI 
            - name: FIREBASE_SDK
              valueFrom:
                secretKeyRef:
                  name: crafty-env
                  key: FIREBASE_SDK

          




