version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    pull_policy: always
    container_name: crafty-backend
    ports:
      - 5000
    # environment:


