
name: Build backend image from develop

on:
  workflow_dispatch:
  push:
    paths:
      - crafty-backend/**
    branches:
      - "develop"
      - "develop-backend"


jobs:
  setup-build-publish:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: develop
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_NAME: ${{ vars.MONGODB_NAME }}
      FIREBASE_SDK: ${{ secrets.FIREBASE_SDK }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SCB_API_KEY: ${{ secrets.SCB_API_KEY }}
      SCB_API_SECRET: ${{ secrets.SCB_API_SECRET }}
      SCB_BILLER_ID: ${{ secrets.SCB_BILLER_ID }}
      SCB_MERCHANT_ID: ${{ secrets.SCB_MERCHANT_ID }}
      SCB_TERMINAL_ID: ${{ secrets.SCB_TERMINAL_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push 
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:crafty-backend"
          push: true
          tags: kuranasaki/crafty-backend:latest,kuranasaki/crafty-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
  deploy:
    name: Deploy to GooseHQ
    needs: 
      - setup-build-publish
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    runs-on: self-hosted
    environment: develop
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_NAME: ${{ vars.MONGODB_NAME }}
      FIREBASE_SDK: ${{ secrets.FIREBASE_SDK }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SCB_API_KEY: ${{ secrets.SCB_API_KEY }}
      SCB_API_SECRET: ${{ secrets.SCB_API_SECRET }}
      SCB_BILLER_ID: ${{ secrets.SCB_BILLER_ID }}
      SCB_MERCHANT_ID: ${{ secrets.SCB_MERCHANT_ID }}
      SCB_TERMINAL_ID: ${{ secrets.SCB_TERMINAL_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: develop-backend
      - name: Pull Image to GooseHQ
        working-directory: ./crafty-backend
        run: docker compose pull
      - name: Deploy to GooseHQ
        working-directory: ./crafty-backend
        run: docker compose up -d