
name: Build backend image from develop

on:
  workflow_dispatch:
  push:
    paths:
      - crafty-backend/**
    branches:
      - "develop"
      - "develop-backend"


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: develop
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_NAME: ${{ vars.MONGODB_NAME }}
      FIREBASE_SDK: ${{ secrets.FIREBASE_SDK }}
    permissions:
      contents: "read"
      id-token: "write"

    steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #     with:
    #       ref: develop
      # - name: Create env file
      #   run: |
      #     touch .env 

      #     echo -e 'MONGODB_URI=${{secrets.MONGODB_URI}}' >> .env
      #     echo -e 'MONGODB_NAME=${{vars.MONGODB_NAME}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_API_KEY=${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_APP_ID=${{vars.NEXT_PUBLIC_FIREBASE_APP_ID}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{vars.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}}' >> .env
      # - name: Set enviroment
      #   run: |
      #     echo "${{secrets.MONGODB_URI}}"" >> $MONGODB_URI
      #     echo "${{vars.MONGODB_NAME}}"" >> $MONGODB_NAME
      #     echo "${{secrets.FIREBASE_SDK}}"" >> $FIREBASE_SDK
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push 
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:crafty-backend"
          push: true
          tags: kuranasaki/crafty-backend:latest,kuranasaki/crafty-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
