
name: Deploy from develop"

on:
  workflow_dispatch:
  push:
    paths:
      - crafty-frontend/**
    branches:
      - "develop"


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: self-hosted
    environment: develop
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      # - name: Create env file
      #   run: |
      #     touch .env 

      #     echo -e 'MONGODB_URI=${{secrets.MONGODB_URI}}' >> .env
      #     echo -e 'MONGODB_NAME=${{vars.MONGODB_NAME}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_API_KEY=${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_APP_ID=${{vars.NEXT_PUBLIC_FIREBASE_APP_ID}}' >> .env
      #     echo -e 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{vars.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}}' >> .env
      - name: Set enviroment
        run: |
          echo "${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}"" >> $NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          echo "${{vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}"" >> $NEXT_PUBLIC_FIREBASE_PROJECT_ID
          echo "${{vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}"" >> $NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
          echo "${{vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}"" >> $NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          echo "${{vars.NEXT_PUBLIC_FIREBASE_APP_ID}}"" >> $NEXT_PUBLIC_FIREBASE_APP_ID
          echo "${{vars.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}}"" >> $NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
      
      - name: Deploy Container
        run: docker-compose -p nex-manager-backend -f ./docker-compose.yaml up -d --build
